version: '3'
services:
  database:
    image: 'postgres:16.2-bookworm'
    environment:
      POSTGRES_DB: $DATABASE_NAME
      POSTGRES_USER: $DATABASE_USER
      POSTGRES_PASSWORD: $DATABASE_PASSWORD
    volumes:
      - 'database:/var/lib/postgresql/data'
  api:
    build:
      dockerfile: dockerfiles/Dockerfile.api
    depends_on:
      - database
    environment:
      DATABASE_USER: $DATABASE_USER
      DATABASE_PASSWORD: $DATABASE_PASSWORD
      DATABASE_HOSTNAME: $DATABASE_HOSTNAME
      DATABASE_PORT: $DATABASE_PORT
      DATABASE_NAME: $DATABASE_NAME
  ui:
    build:
      dockerfile: dockerfiles/Dockerfile.ui
    depends_on:
      - api
    environment:
      API_HOSTNAME: $API_HOSTNAME
      API_PORT: $API_PORT
  nginx:
    build:
      dockerfile: dockerfiles/Dockerfile.server
    ports:
      - '80:80'
    depends_on:
      - ui
volumes:
  database:
    external: false
